# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensors.proto',
  package='sensors',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rsensors.proto\x12\x07sensors\"\\\n\tSensorGPS\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x1e\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x10.sensors.DataGPS\">\n\x07\x44\x61taGPS\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\"\\\n\tSensorIMU\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x1e\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x10.sensors.DataIMU\"*\n\x07\x44\x61taIMU\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\\\n\tSensorDHT\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x1e\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x10.sensors.DataDHT\"0\n\x07\x44\x61taDHT\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x62\x06proto3'
)




_SENSORGPS = _descriptor.Descriptor(
  name='SensorGPS',
  full_name='sensors.SensorGPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='sensors.SensorGPS.device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='sensors.SensorGPS.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sensors.SensorGPS.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='sensors.SensorGPS.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=118,
)


_DATAGPS = _descriptor.Descriptor(
  name='DataGPS',
  full_name='sensors.DataGPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='sensors.DataGPS.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='sensors.DataGPS.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='sensors.DataGPS.height', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=182,
)


_SENSORIMU = _descriptor.Descriptor(
  name='SensorIMU',
  full_name='sensors.SensorIMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='sensors.SensorIMU.device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='sensors.SensorIMU.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sensors.SensorIMU.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='sensors.SensorIMU.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=276,
)


_DATAIMU = _descriptor.Descriptor(
  name='DataIMU',
  full_name='sensors.DataIMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='sensors.DataIMU.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='sensors.DataIMU.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='sensors.DataIMU.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=320,
)


_SENSORDHT = _descriptor.Descriptor(
  name='SensorDHT',
  full_name='sensors.SensorDHT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='sensors.SensorDHT.device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='sensors.SensorDHT.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sensors.SensorDHT.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='sensors.SensorDHT.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=414,
)


_DATADHT = _descriptor.Descriptor(
  name='DataDHT',
  full_name='sensors.DataDHT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='sensors.DataDHT.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='sensors.DataDHT.humidity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=464,
)

_SENSORGPS.fields_by_name['data'].message_type = _DATAGPS
_SENSORIMU.fields_by_name['data'].message_type = _DATAIMU
_SENSORDHT.fields_by_name['data'].message_type = _DATADHT
DESCRIPTOR.message_types_by_name['SensorGPS'] = _SENSORGPS
DESCRIPTOR.message_types_by_name['DataGPS'] = _DATAGPS
DESCRIPTOR.message_types_by_name['SensorIMU'] = _SENSORIMU
DESCRIPTOR.message_types_by_name['DataIMU'] = _DATAIMU
DESCRIPTOR.message_types_by_name['SensorDHT'] = _SENSORDHT
DESCRIPTOR.message_types_by_name['DataDHT'] = _DATADHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorGPS = _reflection.GeneratedProtocolMessageType('SensorGPS', (_message.Message,), {
  'DESCRIPTOR' : _SENSORGPS,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.SensorGPS)
  })
_sym_db.RegisterMessage(SensorGPS)

DataGPS = _reflection.GeneratedProtocolMessageType('DataGPS', (_message.Message,), {
  'DESCRIPTOR' : _DATAGPS,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.DataGPS)
  })
_sym_db.RegisterMessage(DataGPS)

SensorIMU = _reflection.GeneratedProtocolMessageType('SensorIMU', (_message.Message,), {
  'DESCRIPTOR' : _SENSORIMU,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.SensorIMU)
  })
_sym_db.RegisterMessage(SensorIMU)

DataIMU = _reflection.GeneratedProtocolMessageType('DataIMU', (_message.Message,), {
  'DESCRIPTOR' : _DATAIMU,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.DataIMU)
  })
_sym_db.RegisterMessage(DataIMU)

SensorDHT = _reflection.GeneratedProtocolMessageType('SensorDHT', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDHT,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.SensorDHT)
  })
_sym_db.RegisterMessage(SensorDHT)

DataDHT = _reflection.GeneratedProtocolMessageType('DataDHT', (_message.Message,), {
  'DESCRIPTOR' : _DATADHT,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.DataDHT)
  })
_sym_db.RegisterMessage(DataDHT)


# @@protoc_insertion_point(module_scope)
