# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensors.proto',
  package='sensors',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rsensors.proto\x12\x07sensors\">\n\x07\x44\x61taGPS\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\"*\n\x07\x44\x61taIMU\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"0\n\x07\x44\x61taDHT\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x62\x06proto3')
)




_DATAGPS = _descriptor.Descriptor(
  name='DataGPS',
  full_name='sensors.DataGPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='sensors.DataGPS.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='sensors.DataGPS.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='sensors.DataGPS.height', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=88,
)


_DATAIMU = _descriptor.Descriptor(
  name='DataIMU',
  full_name='sensors.DataIMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='sensors.DataIMU.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='sensors.DataIMU.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='sensors.DataIMU.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=132,
)


_DATADHT = _descriptor.Descriptor(
  name='DataDHT',
  full_name='sensors.DataDHT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='sensors.DataDHT.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='sensors.DataDHT.humidity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=182,
)

DESCRIPTOR.message_types_by_name['DataGPS'] = _DATAGPS
DESCRIPTOR.message_types_by_name['DataIMU'] = _DATAIMU
DESCRIPTOR.message_types_by_name['DataDHT'] = _DATADHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataGPS = _reflection.GeneratedProtocolMessageType('DataGPS', (_message.Message,), dict(
  DESCRIPTOR = _DATAGPS,
  __module__ = 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.DataGPS)
  ))
_sym_db.RegisterMessage(DataGPS)

DataIMU = _reflection.GeneratedProtocolMessageType('DataIMU', (_message.Message,), dict(
  DESCRIPTOR = _DATAIMU,
  __module__ = 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.DataIMU)
  ))
_sym_db.RegisterMessage(DataIMU)

DataDHT = _reflection.GeneratedProtocolMessageType('DataDHT', (_message.Message,), dict(
  DESCRIPTOR = _DATADHT,
  __module__ = 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensors.DataDHT)
  ))
_sym_db.RegisterMessage(DataDHT)


# @@protoc_insertion_point(module_scope)
