name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.0
    - name: Compile .proto to cpp and python
      run: for file in *.proto
           do
             protoc --cpp_out="./cpp" --python_out="./python" $file
           done
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff-index --quiet HEAD || git commit -m "generated protobuf classes" -a
    - name: Push Files
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
